# Generated by Django 4.2.5 on 2023-09-18 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_tag', models.CharField(max_length=31)),
                ('cat_name', models.CharField(max_length=63)),
                ('cat_description', models.CharField(max_length=1023)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_tag', models.CharField(max_length=31)),
                ('unit_name', models.CharField(max_length=63)),
                ('unit_okei', models.CharField(blank=True, default='000', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serv_tag', models.CharField(max_length=31)),
                ('serv_name', models.CharField(max_length=63)),
                ('serv_description', models.CharField(max_length=2047)),
                ('serv_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('serv_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skmetr_site.categories')),
                ('serv_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skmetr_site.units')),
            ],
        ),
    ]
