# Generated by Django 4.2.5 on 2023-09-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skmetr_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_email', models.EmailField(max_length=254)),
                ('client_name', models.CharField(blank=True, max_length=64, null=True)),
                ('ticket_subject', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
