# Generated by Django 4.2.5 on 2023-09-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skmetr_site', '0002_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='serv_img',
            field=models.ImageField(blank=True, null=True, upload_to='services'),
        ),
    ]
